CREATE TABLE theater (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(30) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE seat (
  Id INT NOT NULL  AUTO_INCREMENT PRIMARY KEY,
  seatRow VARCHAR(2) NOT NULL ,
  seatNo INT NOT NULL ,
  theaterId INT NOT NULL ,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_TheaterSeat FOREIGN KEY (theaterId) REFERENCES theater(Id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE reservation (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  theaterId INT NOT NULL ,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_TheaterReserve FOREIGN KEY (theaterId) REFERENCES theater(Id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE reservedSeat (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  reservationId INT NOT NULL ,
  theaterId INT NOT NULL,
  seatId INT NOT NULL ,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_TheaterReservedSeat  FOREIGN KEY (theaterId) REFERENCES  theater(Id) ON DELETE RESTRICT ON UPDATE CASCADE ,
  CONSTRAINT FK_ReservationReservedSeat  FOREIGN KEY (reservationId) REFERENCES  reservation(Id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT FK_SeatReservedSeat  FOREIGN KEY (seatId) REFERENCES seat(Id) ON DELETE RESTRICT ON UPDATE CASCADE
);
